backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

#site_url: https://your-site.com
#logo_url: https://your-site.com/images/logo.svg
#publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in this directory
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: 'posts' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Posts' # Used in the UI
    folder: 'content/blog'
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false, format: 'YYYY-MM-DD' }
      - label: 'Categories'
        name: 'categories'
        widget: 'select'
        multiple: true
        options:
          - { label: 'News', value: 'data/categories/news.json' }
          - { label: 'Event', value: 'data/categories/events.json' }   
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        multiple: true
        options:
          - { label: 'Delaware', value: 'data/tags/delaware.json' }
          - { label: 'Hardin', value: 'data/tags/hardin.json' }
          - { label: 'Jackson', value: 'data/tags/jackson.json' }
          - { label: 'Marion', value: 'data/tags/marion.json' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'markdown' }
      - { label: 'Thumbnail Image', name: 'thumb_image', widget: 'image', required: false }
      - { label: 'Thumbnail Image alt text',name: 'thumb_image_alt', widget: 'string' }
      - { label: 'Cover Image', name: 'image', widget: 'image', required: false }
      - { label: 'Cover Image alt text',name: 'image_alt', widget: 'string' }
      - { label: 'Image Position', name: 'image_position', widget: 'hidden', defaut: 'right' } 
      - { label: 'Layout', name: 'layout', widget: 'hidden', defaut: 'post' } 
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
  
#  - name: 'locations' # Used in routes, ie.: /admin/collections/:slug/edit
#    label: 'Locations' # Used in the UI
#    folder: 'content/locations'
#    slug: '{{slug}}'
#    create: true # Allow users to create new documents in this collection
#    fields: # The fields each document in this collection have
#      - { label: 'Title', name: 'title', widget: 'string' }
#      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
#      - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false, format: 'YYYY-MM-DD' }
#      - label: 'Categories'
#        name: 'categories'
#        widget: 'select'
#        multiple: true
#        options:
#          - { label: 'News', value: 'data/categories/news.json' }
#          - { label: 'Event', value: 'data/categories/events.json' }   
#      - label: 'Tags'
#        name: 'tags'
#        widget: 'select'
#        multiple: true
#        options:
#          - { label: 'Delaware', value: 'data/tags/delaware.json' }
#          - { label: 'Hardin', value: 'data/tags/hardin.json' }
#          - { label: 'Jackson', value: 'data/tags/jackson.json' }
#          - { label: 'Marion', value: 'data/tags/marion.json' }
#      - { label: 'Excerpt', name: 'excerpt', widget: 'markdown' }
#      - { label: 'Thumbnail Image', name: 'thumb_image', widget: 'image', required: false }
#      - { label: 'Thumbnail Image alt text', name: 'thumb_image_alt', widget: 'string' }
#      - { label: 'Cover Image', name: 'image', widget: 'image', required: false }
#      - { label: 'Cover Image alt text', name: 'image_alt', widget: 'string' }
#      - { label: 'Image Position', name: 'image_position', widget: 'hidden', defaut: 'right' }
#      - label: 'SEO'
#        name: 'seo'
#        widget: 'object'
#        collapsed: true
#        fields: 
#          - {label: 'Title', name: 'title', widget: 'string'}
#          - {label: 'Description', name: 'description', widget: 'string'}
#          - label: 'Extra'
#            name: 'extra'
#            widget: 'list'
#            fields:
#              - { label: 'Name', name: 'name', widget: 'string'}
#              - { label: 'Value', name: 'value', widget: 'string'}
#              - { label: 'keyName', name: 'keyName', widget: 'hidden', default: 'property'}
#      - { label: 'Layout', name: 'layout', widget: 'hidden', defaut: 'advanced' }
#  
#  - name: 'pages'
#    label: 'Pages'
#    files:
#      - label: 'About Page'
#        name: 'about'
#        file: 'content/about.md'
#        fields:
#          - {label: Title, name: title, widget: string}
#          - {label: Intro, name: intro, widget: markdown}
#          - label: Team
#            name: team
#            widget: list
#            fields:
#              - {label: Name, name: name, widget: string}
#              - {label: Position, name: position, widget: string}
#              - {label: Photo, name: photo, widget: image}
#      - label: 'Contact Page'
#        name: 'contact'
#        file: 'content/contact.md'
#        fields:
#          - {label: Title, name: title, widget: string}
#          - {label: Intro, name: intro, widget: markdown}
#          - label: Locations
#            name: locations
#            widget: list
#            fields:
#              - {label: Name, name: name, widget: string}
#              - {label: Address, name: address, widget: string}
#      - label: 'Get Involved Page'
#        name: 'involved'
#        file: 'content/get-involved.md'
#        fields:
#          - {label: Title, name: title, widget: string}
#          - {label: Intro, name: intro, widget: markdown}
#          - label: Locations
#            name: locations
#            widget: list
#            fields:
#              - {label: Name, name: name, widget: string}
#              - {label: Address, name: address, widget: string}
#      - label: 'Patients Page'
#        name: 'patients'
#        file: 'content/patients.md'
#        fields:
#          - {label: Title, name: title, widget: string}
#          - {label: Intro, name: intro, widget: markdown}
#          - label: Locations
#            name: locations
#            widget: list
#            fields:
#              - {label: Name, name: name, widget: string}
#              - {label: Address, name: address, widget: string}